-- Create "orgs" table
CREATE TABLE "orgs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "waves" table
CREATE TABLE "waves" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "org_waves" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "waves_orgs_waves" FOREIGN KEY ("org_waves") REFERENCES "orgs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "vtubers" table
CREATE TABLE "vtubers" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "channel_name" character varying NOT NULL, "youtube_channel_id" character varying NOT NULL, "english_name" character varying NULL, "photo_url" character varying NULL, "banner_url" character varying NULL, "twitter" character varying NULL, "video_count" bigint NULL, "subscriber_count" bigint NULL, "clip_count" bigint NULL, "top_topics" jsonb NULL, "description" character varying NULL, "inactive" boolean NOT NULL, "twitch" character varying NULL, "wave_vtubers" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "vtubers_waves_vtubers" FOREIGN KEY ("wave_vtubers") REFERENCES "waves" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "reported_streams" table
CREATE TABLE "reported_streams" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "video_id" character varying NOT NULL, "vtuber_id" bigint NOT NULL, "available_at" timestamptz NOT NULL, "vtuber_repoted_streams" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "reported_streams_vtubers_repoted_streams" FOREIGN KEY ("vtuber_repoted_streams") REFERENCES "vtubers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tg_id" bigint NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NULL, "username" character varying NULL, "language_code" character varying NULL, "photo_url" character varying NULL, "timezone_shift" bigint NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "users_tg_id_key" to table: "users"
CREATE UNIQUE INDEX "users_tg_id_key" ON "users" ("tg_id");
-- Create "user_vtubers" table
CREATE TABLE "user_vtubers" ("user_id" bigint NOT NULL, "vtuber_id" bigint NOT NULL, PRIMARY KEY ("user_id", "vtuber_id"), CONSTRAINT "user_vtubers_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_vtubers_vtuber_id" FOREIGN KEY ("vtuber_id") REFERENCES "vtubers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
