-- Create "queue_scheduled_tasks" table
CREATE TABLE "queue_scheduled_tasks" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL UNIQUE, "interval" bigint NOT NULL, "last_run_timestamp" timestamptz NOT NULL, "status" character varying NOT NULL, PRIMARY KEY ("id"));
