-- Create "queue_tasks" table
CREATE TABLE "queue_tasks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "task_name" character varying NOT NULL,
  "data" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
