version: "3"

services:
  backend:
    restart: always
    build: ../backend
    image: ${REGISTRY}/vtuber-go-backend:${TAG}
    command: ["--config", "./config.yaml"]
    volumes:
      - ./config.yaml:/opt/vtuber-go/config.yaml:ro
    expose:
      - 8000
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
       interval: 5s
       timeout: 5s
       retries: 5
  migrate:
    image: arigaio/atlas
    volumes:
      - ../ent/migrate/migrations:/migrations:ro
    restart: on-failure:5
    command: >
        migrate apply
        --url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ../frontend
    image: ${REGISTRY}/vtuber-go-frontend:${TAG}
    expose:
      - 8000
    environment:
      SERVER_NAME: ${SERVER_NAME}
  gateway:
    image: nginx:latest
    volumes:
      - ./gateway/gateway.conf.template:/etc/nginx/templates/gateway.conf.template:ro
    ports:
      - 8000:8000
    environment:
      SERVER_NAME: ${SERVER_NAME}